/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import notif.login.*;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.*;
/**
 *
 * @author lenovo
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form landing
     */
    public login() {
        initComponents();
        this.hideEye.setVisible(false);
    }
    public void removePlaceHolderStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hideEye = new javax.swing.JLabel();
        unhideEye = new javax.swing.JLabel();
        t_username = new javax.swing.JTextField();
        t_password = new javax.swing.JPasswordField();
        b_login = new javax.swing.JLabel();
        b_lupapass = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hideEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/eye_hide.png"))); // NOI18N
        hideEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hideEyeMousePressed(evt);
            }
        });
        getContentPane().add(hideEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 410, 20, 20));

        unhideEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/eye.png"))); // NOI18N
        unhideEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                unhideEyeMousePressed(evt);
            }
        });
        getContentPane().add(unhideEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 410, -1, -1));

        t_username.setBackground(new Color(0,0,0,0));
        t_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_username.setBorder(null);
        t_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_usernameFocusLost(evt);
            }
        });
        t_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(t_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 270, 360, 60));

        t_password.setBackground(new Color(0,0,0,0));
        t_password.setBorder(null);
        t_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t_passwordMousePressed(evt);
            }
        });
        t_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(t_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 380, 360, 70));

        b_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_loginMouseClicked(evt);
            }
        });
        getContentPane().add(b_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 520, 200, 60));

        b_lupapass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_lupapassMouseClicked(evt);
            }
        });
        getContentPane().add(b_lupapass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 460, 130, 30));

        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
        });
        getContentPane().add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 10, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Login Page.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_usernameActionPerformed

    private void b_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_loginMouseClicked
        String username = t_username.getText();
        String password = t_password.getText();
        Logic.LogicLogin login = new Logic.LogicLogin();
        boolean logg = login.log(username, password);
        if(logg){
            String lvl = Logic.LogicLogin.level;
            this.setVisible(true);
            if(lvl.equals("owner")){   
                Floginberhasilowner owner = new Floginberhasilowner();
                owner.setVisible(true);
            }else if(lvl.equals("admin toko")){
                Floginberhasiladmin admin = new Floginberhasiladmin();
                admin.setVisible(true);
            }  
        }else{
             Flogingagal gagal = new Flogingagal();
             gagal.setVisible(true);
        }
        
    }//GEN-LAST:event_b_loginMouseClicked

    private void b_lupapassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_lupapassMouseClicked
        this.setVisible(false);
        new lupa1().setVisible(true);
    }//GEN-LAST:event_b_lupapassMouseClicked

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
        this.dispose();
    }//GEN-LAST:event_exit1MouseClicked

    private void unhideEyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unhideEyeMousePressed
        hideEye.setVisible(true);
        unhideEye.setVisible(false);
        t_password.setEchoChar('*');
    }//GEN-LAST:event_unhideEyeMousePressed

    private void hideEyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideEyeMousePressed
        unhideEye.setVisible(true);
        hideEye.setVisible(false);
        t_password.setEchoChar((char)0);
    }//GEN-LAST:event_hideEyeMousePressed

    private void t_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_passwordMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passwordMousePressed

    private void t_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passwordActionPerformed

    private void t_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusGained
        if(t_username.getText().equals("Masukkan Username")){
            t_username.setText(null);
            t_username.requestFocus();
            removePlaceHolderStyle(t_username);
        }
    }//GEN-LAST:event_t_usernameFocusGained

    private void t_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusLost

    }//GEN-LAST:event_t_usernameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_login;
    private javax.swing.JLabel b_lupapass;
    private javax.swing.JLabel background;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel hideEye;
    private javax.swing.JPasswordField t_password;
    private javax.swing.JTextField t_username;
    private javax.swing.JLabel unhideEye;
    // End of variables declaration//GEN-END:variables
}
