/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import java.awt.*;
import notif.login.*;

/**
 *
 * @author lenovo
 */
public class lupa2 extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public lupa2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unhideEye = new javax.swing.JLabel();
        hideEye = new javax.swing.JLabel();
        unhideEye1 = new javax.swing.JLabel();
        hideEye1 = new javax.swing.JLabel();
        txt_newpass = new javax.swing.JPasswordField();
        txt_validpass = new javax.swing.JPasswordField();
        t_ubahpass = new javax.swing.JLabel();
        btnexit = new javax.swing.JLabel();
        btnback = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        unhideEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_show.png"))); // NOI18N
        unhideEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                unhideEyeMousePressed(evt);
            }
        });
        getContentPane().add(unhideEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 280, 30, 30));

        hideEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_hide.png"))); // NOI18N
        hideEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hideEyeMousePressed(evt);
            }
        });
        getContentPane().add(hideEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 280, 30, 30));

        unhideEye1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_show.png"))); // NOI18N
        unhideEye1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                unhideEye1MousePressed(evt);
            }
        });
        getContentPane().add(unhideEye1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 400, 30, 30));

        hideEye1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_hide.png"))); // NOI18N
        hideEye1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hideEye1MousePressed(evt);
            }
        });
        getContentPane().add(hideEye1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 400, 30, 30));

        txt_newpass.setBackground(new Color(0,0,0,0));
        txt_newpass.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        txt_newpass.setBorder(null);
        getContentPane().add(txt_newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, 380, 60));

        txt_validpass.setBackground(new Color(0,0,0,0));
        txt_validpass.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        txt_validpass.setBorder(null);
        txt_validpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_validpassActionPerformed(evt);
            }
        });
        getContentPane().add(txt_validpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 380, 380, 70));

        t_ubahpass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t_ubahpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_ubahpassMouseClicked(evt);
            }
        });
        getContentPane().add(t_ubahpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 480, 190, 70));

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_exit.png"))); // NOI18N
        btnexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexitMouseClicked(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 20, -1, -1));

        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_previous.png"))); // NOI18N
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ChangePassword.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t_ubahpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_ubahpassMouseClicked
        String newpassword = txt_newpass.getText();
        String validPassword = txt_validpass.getText();
        if(newpassword.equals(validPassword)){
            if(newpassword.length() >= 8){
            Logic.LogicLogin login = new Logic.LogicLogin();
            boolean konfirmasi = login.changePassword(newpassword);
            new Fpasswordubah().setVisible(konfirmasi);
            }else{
              Fpasswordkurang kurang = new Fpasswordkurang();
              kurang.setVisible(true);
            }
        }else{
            Fpasswordbeda beda = new Fpasswordbeda();
            beda.setVisible(true);
        }
    }//GEN-LAST:event_t_ubahpassMouseClicked

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        new lupa1().setVisible(true);
    }//GEN-LAST:event_btnbackMouseClicked

    private void btnexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnexitMouseClicked

    private void txt_validpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_validpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_validpassActionPerformed

    private void unhideEyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unhideEyeMousePressed
        hideEye.setVisible(true);
        unhideEye.setVisible(false);
        txt_newpass.setEchoChar((char)0);
    }//GEN-LAST:event_unhideEyeMousePressed

    private void hideEyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideEyeMousePressed
        unhideEye.setVisible(true);
        hideEye.setVisible(false);
        txt_newpass.setEchoChar('*');
    }//GEN-LAST:event_hideEyeMousePressed

    private void unhideEye1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unhideEye1MousePressed
        hideEye.setVisible(true);
        unhideEye.setVisible(false);
        txt_validpass.setEchoChar((char)0);
    }//GEN-LAST:event_unhideEye1MousePressed

    private void hideEye1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideEye1MousePressed
        unhideEye.setVisible(true);
        hideEye.setVisible(false);
        txt_validpass.setEchoChar('*');
    }//GEN-LAST:event_hideEye1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lupa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lupa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lupa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lupa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lupa2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnback;
    private javax.swing.JLabel btnexit;
    private javax.swing.JLabel hideEye;
    private javax.swing.JLabel hideEye1;
    private javax.swing.JLabel t_ubahpass;
    private javax.swing.JPasswordField txt_newpass;
    private javax.swing.JPasswordField txt_validpass;
    private javax.swing.JLabel unhideEye;
    private javax.swing.JLabel unhideEye1;
    // End of variables declaration//GEN-END:variables
}
