/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.*;
import java.awt.*;
import notif.login.*;

/**
 *
 * @author lenovo
 */
public class lupa1 extends javax.swing.JFrame {

    /**
     * Creates new form lupa1
     */
    public lupa1() {
        initComponents();
        popUp_PINSalah.setVisible(false);
        popUp_PINValid.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp_PINSalah = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        popUp_PINValid = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        b_lanjut = new javax.swing.JLabel();
        unhideEye = new javax.swing.JLabel();
        hideEye = new javax.swing.JLabel();
        txt_username1 = new javax.swing.JTextField();
        txt_pin = new javax.swing.JPasswordField();
        b_exit = new javax.swing.JLabel();
        b_back = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        popUp_PINSalah.setBackground(new Color(0,0,0,200));
        popUp_PINSalah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                popUp_PINSalahMousePressed(evt);
            }
        });
        popUp_PINSalah.setLayout(null);

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        popUp_PINSalah.add(jLabel5);
        jLabel5.setBounds(630, 420, 170, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/popup pin tidak sesuai.png"))); // NOI18N
        popUp_PINSalah.add(jLabel6);
        jLabel6.setBounds(360, 210, 720, 300);

        getContentPane().add(popUp_PINSalah);
        popUp_PINSalah.setBounds(0, 0, 1464, 789);

        popUp_PINValid.setBackground(new Color(0,0,0,150));
        popUp_PINValid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                popUp_PINValidMousePressed(evt);
            }
        });
        popUp_PINValid.setLayout(null);

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        popUp_PINValid.add(jLabel7);
        jLabel7.setBounds(630, 400, 180, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/notif/login/Pinberhasil.png"))); // NOI18N
        popUp_PINValid.add(jLabel8);
        jLabel8.setBounds(380, 180, 720, 310);

        getContentPane().add(popUp_PINValid);
        popUp_PINValid.setBounds(0, 0, 1464, 789);

        b_lanjut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_lanjut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_lanjutMouseClicked(evt);
            }
        });
        getContentPane().add(b_lanjut);
        b_lanjut.setBounds(980, 480, 240, 70);

        unhideEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_show.png"))); // NOI18N
        unhideEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                unhideEyeMousePressed(evt);
            }
        });
        getContentPane().add(unhideEye);
        unhideEye.setBounds(1250, 400, 30, 30);

        hideEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_hide.png"))); // NOI18N
        hideEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hideEyeMousePressed(evt);
            }
        });
        getContentPane().add(hideEye);
        hideEye.setBounds(1250, 400, 30, 30);

        txt_username1.setBackground(new Color(0,0,0,0));
        txt_username1.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        txt_username1.setBorder(null);
        txt_username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_username1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username1);
        txt_username1.setBounds(900, 270, 380, 60);

        txt_pin.setBackground(new Color(0,0,0,0));
        txt_pin.setFont(new java.awt.Font("Microsoft Tai Le", 0, 48)); // NOI18N
        txt_pin.setBorder(null);
        getContentPane().add(txt_pin);
        txt_pin.setBounds(900, 380, 370, 70);

        b_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_exit.png"))); // NOI18N
        b_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_exitMouseClicked(evt);
            }
        });
        getContentPane().add(b_exit);
        b_exit.setBounds(1270, 20, 51, 51);

        b_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_previous.png"))); // NOI18N
        b_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_backMouseClicked(evt);
            }
        });
        getContentPane().add(b_back);
        b_back.setBounds(1210, 20, 50, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ForgetPassword.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1464, 789);

        setSize(new java.awt.Dimension(1464, 789));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_lanjutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_lanjutMouseClicked
        String username = txt_username1.getText();
        String pin = txt_pin.getText();
         Logic.LogicLogin login = new Logic.LogicLogin();
         boolean konfirmasi = login.forgetPassword(username,pin);
         if(konfirmasi){
             popUp_PINValid.setVisible(true);
         }else{
             popUp_PINSalah.setVisible(true);
         }
    }//GEN-LAST:event_b_lanjutMouseClicked

    private void txt_username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_username1ActionPerformed

    private void b_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_backMouseClicked
         new login().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_b_backMouseClicked

    private void b_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_b_exitMouseClicked

    private void unhideEyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unhideEyeMousePressed
        hideEye.setVisible(true);
        unhideEye.setVisible(false);
        txt_pin.setEchoChar((char)0);
    }//GEN-LAST:event_unhideEyeMousePressed

    private void hideEyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideEyeMousePressed
        unhideEye.setVisible(true);
        hideEye.setVisible(false);
        txt_pin.setEchoChar('*');
    }//GEN-LAST:event_hideEyeMousePressed

    private void popUp_PINSalahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popUp_PINSalahMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_popUp_PINSalahMousePressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        popUp_PINSalah.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void popUp_PINValidMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popUp_PINValidMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_popUp_PINValidMousePressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.dispose();
        new lupa1().setVisible(false);
        new lupa2().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lupa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lupa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lupa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lupa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lupa1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_back;
    private javax.swing.JLabel b_exit;
    private javax.swing.JLabel b_lanjut;
    private javax.swing.JLabel background;
    private javax.swing.JLabel hideEye;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel popUp_PINSalah;
    private javax.swing.JPanel popUp_PINValid;
    private javax.swing.JPasswordField txt_pin;
    private javax.swing.JTextField txt_username1;
    private javax.swing.JLabel unhideEye;
    // End of variables declaration//GEN-END:variables
}
